name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Check frontend style
        run: npm run lint
        working-directory: frontend

      - name: Run frontend tests
        run: npm test
        working-directory: frontend

      - name: Run backend tests
        run: npm test
        working-directory: backend
        env:
          MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}

      - name: Build frontend
        run: npm run build
        working-directory: frontend

  deploy:
    needs: [build_and_test]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  notify_success:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Success
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: success
          content: "A new version of Blogapp gets deployed successfully!"
          title: "Deployment Succeeded"

  notify_failure:
    needs: [build_and_test, deploy]
    if: ${{ always() && (needs.build_and_test.result == 'failure' || needs.deploy.result == 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Failure
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: failure
          content: "Pipeline failed! Commit: ${{ github.sha }} by ${{ github.actor }}"
          title: "Pipeline Failed"

  tag_release:
    needs: [deploy]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch